# copied from https://jupyterbook.org/publish/gh-pages.html?highlight=github%20pages

name: test-build

# Only run this when a PR suggests changes to main branch
on:
  pull_request:
    branches:
      - main

# This job installs dependencies and builds the book
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install MyST
        run: npm install -g mystmd@1.6.4
      - name: Build HTML Assets
        working-directory: book
        run: myst build --html
